### ISSUE TITLE
Trying to setup caddy with porkbun using xcaddy

### ISSUE THREAD

**Issue by ALMerrill** [Niallfitzy1/caddy-dns-porkbun#1]
I'm trying to run `xcaddy build --with github.com/Niallfitzy1/caddy-dns-porkbun` in order to setup caddy to work with my porkbun domain. Looks like there's a `comn` somewhere that's messing it up? I'm pretty new to dns and domain management and what not. Do you know how I can get around this?

OS: Raspberry PI 4
go version: 1.18 
```
go: github.com/Niallfitzy1/caddy-dns-porkbun@v0.0.1 requires
        github.com/Niallfitzy1/libdns@v0.0.1: parsing go.mod:
        module declares its path as: github.comn/Niallfitzy1/libdns-porkbun
                but was required as: github.com/Niallfitzy1/libdns
```

**Comment by Niallfitzy1** [comment]
@ALMerrill Sorry about the slow response. The fixed version is available here:
[caddy-dns/porkbun v0.1.0](https://github.com/caddy-dns/porkbun/releases/tag/v0.1.0) 

```shell
xcaddy build --with github.com/caddy-dns/porkbun
```
